language: java
jdk:
  - openjdk8
stages:
  - install-gradle
  - compile
  - check
  - deploy
  - post-deploy
jobs:
  include:
    - stage: install-gradle
      name: "install gradle"
      install:
        - chmod +x gradlew
        - chmod +x gradle/wrapper/gradle-wrapper.jar
      script: skip
    - stage: compile
      name: "compile without running any test"
      script: ./gradlew clean build -x test
    - stage: check
      name: "check the project"
      script: ./gradlew check
    - stage: deploy
      name: "fake deployment"
      script: skip
    - stage: post-deploy
      name: "post deploy"
      script: ls -la
